In [4]:
import pandas as pd

In [5]:
df_main = pd.read_csv('df_main.csv', index_col=0).reset_index(drop=True)

In [6]:
df_main

,fips,Staffed_Beds,Total_Discharges,Patient_Days,Gross_Patient_Revenue,Hospitals,Local_Hospital,ADI_NATRANK,ADI_STATERNK,2021/3/10_x,...,pct_veterans_male,pop_adult_education_bachelors_or_higher,pop_adult_education_high_school,pop_adult_education_less_than_high_school,pop_adult_education_some_college_or_associates,pop_lived_in_same_house_last_year,pop_total,pop_veterans,pop_veterans_female,pop_veterans_male
0,1001,77.0,3049.0,15984.0,250284.0,1.0,yes,66.977778,4.355556,6400.0,...,88.111428,8464,8819,2886,9201,48039.0,55639,4559,542,4017
1,1003,301.0,18080.0,78361.0,2481966.0,3.0,yes,51.534483,2.655172,20012.0,...,91.796182,36513,29636,10250,34448,191350.0,218289,19174,1573,17601
2,1005,47.0,1055.0,4571.0,76099.0,1.0,yes,90.900000,7.950000,2161.0,...,92.014925,1409,4525,3131,3955,20996.0,25026,1340,107,1233
3,1007,156.0,229.0,1053.0,31288.0,1.0,yes,83.411765,6.647059,2469.0,...,94.771783,1388,5442,2189,3292,19347.0,22374,1205,63,1142
4,1009,0.0,0.0,0.0,0.0,0.0,no,72.325581,4.906977,6260.0,...,93.603286,4158,9757,4494,11023,52428.0,57755,3408,218,3190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,56037,58.0,1279.0,4742.0,207720.0,2.0,yes,54.088235,6.147059,3861.0,...,92.318291,5084,7298,1656,8906,34743.0,43352,2903,223,2680
3120,56039,121.0,1711.0,5932.0,273723.0,1.0,yes,6.473684,1.000000,3404.0,...,88.149938,7762,2278,871,3390,18448.0,23356,827,98,729
3121,56041,32.0,803.0,1627.0,105109.0,1.0,yes,57.058824,7.117647,2084.0,...,92.226890,1974,3960,664,3627,17520.0,20374,952,74,878
3122,56043,0.0,0.0,0.0,0.0,0.0,no,59.555556,7.777778,888.0,...,96.088434,1013,1021,308,1457,6667.0,7933,588,23,565
3123,56045,0.0,0.0,0.0,0.0,0.0,no,63.600000,8.600000,623.0,...,92.831540,668,1312,199,1346,5472.0,6942,558,40,518

In [7]:
print(list(df_main.columns))

['fips', 'Staffed_Beds', 'Total_Discharges', 'Patient_Days', 'Gross_Patient_Revenue', 'Hospitals', 'Local_Hospital', 'ADI_NATRANK', 'ADI_STATERNK', '2021/3/10_x', '2022/3/10_x', '2023/3/10_x', '2021/3/10_y', '2022/3/10_y', '2023/3/10_y', 'Value_education', 'Value_poverty', 'Value_unemployment', 'pct_pop_commute_departure_0000_to_0459', 'pct_pop_commute_departure_0500_to_0529', 'pct_pop_commute_departure_0530_to_0559', 'pct_pop_commute_departure_0600_to_0629', 'pct_pop_commute_departure_0630_to_0659', 'pct_pop_commute_departure_0700_to_0729', 'pct_pop_commute_departure_0730_to_0759', 'pct_pop_commute_departure_0800_to_0829', 'pct_pop_commute_departure_0830_to_0859', 'pct_pop_commute_departure_0900_to_0959', 'pct_pop_commute_departure_1000_to_1059', 'pct_pop_commute_departure_1100_to_1159', 'pct_pop_commute_departure_1200_to_1559', 'pct_pop_commute_departure_1600_to_2359', 'pct_pop_commute_travel_time_10_to_14_min', 'pct_pop_commute_travel_time_15_to_19_min', 'pct_pop_commute_travel_time_20_to_24_min', 'pct_pop_commute_travel_time_25_to_29_min', 'pct_pop_commute_travel_time_30_to_34_min', 'pct_pop_commute_travel_time_35_to_39_min', 'pct_pop_commute_travel_time_40_to_44_min', 'pct_pop_commute_travel_time_45_to_59_min', 'pct_pop_commute_travel_time_5_to_9_min', 'pct_pop_commute_travel_time_60_to_89_min', 'pct_pop_commute_travel_time_90_min_or_more', 'pct_pop_commute_travel_time_under_5_min', 'pct_pop_commutes_by_bicycle', 'pct_pop_commutes_by_car_truck_van_alone', 'pct_pop_commutes_by_car_truck_van_any', 'pct_pop_commutes_by_car_truck_van_carpool', 'pct_pop_commutes_by_public_transport_any', 'pct_pop_commutes_by_public_transport_bus', 'pct_pop_commutes_by_public_transport_ferry', 'pct_pop_commutes_by_public_transport_lightrail', 'pct_pop_commutes_by_public_transport_rail', 'pct_pop_commutes_by_public_transport_subway', 'pct_pop_commutes_by_taxi_motorcycle_or_other', 'pct_pop_commutes_by_walking', 'pct_pop_has_0_vehicles_available', 'pct_pop_has_1_vehicles_available', 'pct_pop_has_2_vehicles_available', 'pct_pop_has_3_or_more_vehicles_available', 'pct_pop_works_from_home', 'pct_pop_works_in_county_of_residence', 'pct_pop_works_in_state_different_county_of_residence', 'pct_pop_works_in_state_of_residence', 'pct_pop_works_outside_state_of_residence', 'pop_commute_departure_0000_to_0459', 'pop_commute_departure_0500_to_0529', 'pop_commute_departure_0530_to_0559', 'pop_commute_departure_0600_to_0629', 'pop_commute_departure_0630_to_0659', 'pop_commute_departure_0700_to_0729', 'pop_commute_departure_0730_to_0759', 'pop_commute_departure_0800_to_0829', 'pop_commute_departure_0830_to_0859', 'pop_commute_departure_0900_to_0959', 'pop_commute_departure_1000_to_1059', 'pop_commute_departure_1100_to_1159', 'pop_commute_departure_1200_to_1559', 'pop_commute_departure_1600_to_2359', 'pop_commute_travel_time_10_to_14_min', 'pop_commute_travel_time_15_to_19_min', 'pop_commute_travel_time_20_to_24_min', 'pop_commute_travel_time_25_to_29_min', 'pop_commute_travel_time_30_to_34_min', 'pop_commute_travel_time_35_to_39_min', 'pop_commute_travel_time_40_to_44_min', 'pop_commute_travel_time_45_to_59_min', 'pop_commute_travel_time_5_to_9_min', 'pop_commute_travel_time_60_to_89_min', 'pop_commute_travel_time_90_min_or_more', 'pop_commute_travel_time_under_5_min', 'pop_commutes_by_bicycle', 'pop_commutes_by_car_truck_van_alone', 'pop_commutes_by_car_truck_van_any', 'pop_commutes_by_car_truck_van_carpool', 'pop_commutes_by_public_transport_any', 'pop_commutes_by_public_transport_bus', 'pop_commutes_by_public_transport_ferry', 'pop_commutes_by_public_transport_lightrail', 'pop_commutes_by_public_transport_rail', 'pop_commutes_by_public_transport_subway', 'pop_commutes_by_taxi_motorcycle_or_other', 'pop_commutes_by_walking', 'pop_has_0_vehicles_available', 'pop_has_1_vehicles_available', 'pop_has_2_vehicles_available', 'pop_has_3_or_more_vehicles_available', 'pop_works_from_home', 'pop_works_in_county_of_residence', 'pop_works_in_state_different_county_of_residence', 'pop_works_in_state_of_residence', 'pop_works_outside_state_of_residence', 'geometry_x', 'median_age', 'median_age_female', 'median_age_male', 'pct_pop_birthplace_foreign', 'pct_pop_birthplace_us', 'pct_pop_citizenship_non_us', 'pct_pop_citizenship_us_native', 'pct_pop_citizenship_us_naturalized', 'pct_pop_ethnicity_hispanic_latino', 'pct_pop_ethnicity_non_hispanic', 'pct_pop_race_asian', 'pct_pop_race_black', 'pct_pop_race_hawaiian_pacific_islander', 'pct_pop_race_multiple', 'pct_pop_race_native_american', 'pct_pop_race_other', 'pct_pop_race_white', 'pct_pop_sex_female', 'pct_pop_sex_female_age_10_to_14', 'pct_pop_sex_female_age_15_to_17', 'pct_pop_sex_female_age_18_to_19', 'pct_pop_sex_female_age_20', 'pct_pop_sex_female_age_21', 'pct_pop_sex_female_age_22_to_24', 'pct_pop_sex_female_age_25_to_29', 'pct_pop_sex_female_age_30_to_34', 'pct_pop_sex_female_age_35_to_39', 'pct_pop_sex_female_age_40_to_44', 'pct_pop_sex_female_age_45_to_49', 'pct_pop_sex_female_age_50_to_54', 'pct_pop_sex_female_age_55_to_59', 'pct_pop_sex_female_age_5_to_9', 'pct_pop_sex_female_age_60_to_61', 'pct_pop_sex_female_age_62_to_64', 'pct_pop_sex_female_age_65_to_66', 'pct_pop_sex_female_age_67_to_69', 'pct_pop_sex_female_age_70_to_74', 'pct_pop_sex_female_age_75_to_79', 'pct_pop_sex_female_age_80_to_84', 'pct_pop_sex_female_age_85_and_over', 'pct_pop_sex_female_age_under_5', 'pct_pop_sex_male', 'pct_pop_sex_male_age_10_to_14', 'pct_pop_sex_male_age_15_to_17', 'pct_pop_sex_male_age_18_to_19', 'pct_pop_sex_male_age_20', 'pct_pop_sex_male_age_21', 'pct_pop_sex_male_age_22_to_24', 'pct_pop_sex_male_age_25_to_29', 'pct_pop_sex_male_age_30_to_34', 'pct_pop_sex_male_age_35_to_39', 'pct_pop_sex_male_age_40_to_44', 'pct_pop_sex_male_age_45_to_49', 'pct_pop_sex_male_age_50_to_54', 'pct_pop_sex_male_age_55_to_59', 'pct_pop_sex_male_age_5_to_9', 'pct_pop_sex_male_age_60_to_61', 'pct_pop_sex_male_age_62_to_64', 'pct_pop_sex_male_age_65_to_66', 'pct_pop_sex_male_age_67_to_69', 'pct_pop_sex_male_age_70_to_74', 'pct_pop_sex_male_age_75_to_79', 'pct_pop_sex_male_age_80_to_84', 'pct_pop_sex_male_age_85_and_over', 'pct_pop_sex_male_age_under_5', 'pop_birthplace_foreign', 'pop_birthplace_us', 'pop_citizenship_non_us', 'pop_citizenship_us_native', 'pop_citizenship_us_naturalized', 'pop_ethnicity_hispanic_latino', 'pop_ethnicity_non_hispanic', 'pop_race_asian', 'pop_race_black', 'pop_race_hawaiian_pacific_islander', 'pop_race_multiple', 'pop_race_native_american', 'pop_race_other', 'pop_race_white', 'pop_sex_female', 'pop_sex_female_age_10_to_14', 'pop_sex_female_age_15_to_17', 'pop_sex_female_age_18_to_19', 'pop_sex_female_age_20', 'pop_sex_female_age_21', 'pop_sex_female_age_22_to_24', 'pop_sex_female_age_25_to_29', 'pop_sex_female_age_30_to_34', 'pop_sex_female_age_35_to_39', 'pop_sex_female_age_40_to_44', 'pop_sex_female_age_45_to_49', 'pop_sex_female_age_50_to_54', 'pop_sex_female_age_55_to_59', 'pop_sex_female_age_5_to_9', 'pop_sex_female_age_60_to_61', 'pop_sex_female_age_62_to_64', 'pop_sex_female_age_65_to_66', 'pop_sex_female_age_67_to_69', 'pop_sex_female_age_70_to_74', 'pop_sex_female_age_75_to_79', 'pop_sex_female_age_80_to_84', 'pop_sex_female_age_85_and_over', 'pop_sex_female_age_under_5', 'pop_sex_male', 'pop_sex_male_age_10_to_14', 'pop_sex_male_age_15_to_17', 'pop_sex_male_age_18_to_19', 'pop_sex_male_age_20', 'pop_sex_male_age_21', 'pop_sex_male_age_22_to_24', 'pop_sex_male_age_25_to_29', 'pop_sex_male_age_30_to_34', 'pop_sex_male_age_35_to_39', 'pop_sex_male_age_40_to_44', 'pop_sex_male_age_45_to_49', 'pop_sex_male_age_50_to_54', 'pop_sex_male_age_55_to_59', 'pop_sex_male_age_5_to_9', 'pop_sex_male_age_60_to_61', 'pop_sex_male_age_62_to_64', 'pop_sex_male_age_65_to_66', 'pop_sex_male_age_67_to_69', 'pop_sex_male_age_70_to_74', 'pop_sex_male_age_75_to_79', 'pop_sex_male_age_80_to_84', 'pop_sex_male_age_85_and_over', 'pop_sex_male_age_under_5', 'pop_total_x', 'geometry_y', 'households_total_x', 'households_with_annual_income_100000_to_124999', 'households_with_annual_income_125000_to_149999', 'households_with_annual_income_150000_to_199999', 'households_with_annual_income_200000_or_more', 'households_with_annual_income_30000_to_39999', 'households_with_annual_income_40000_to_49999', 'households_with_annual_income_50000_to_59999', 'households_with_annual_income_60000_to_75499', 'households_with_annual_income_75000_to_99999', 'households_with_annual_income_less_than_30000', 'pct_households_with_annual_income_100000_to_124999', 'pct_households_with_annual_income_125000_to_149999', 'pct_households_with_annual_income_150000_to_199999', 'pct_households_with_annual_income_200000_or_more', 'pct_households_with_annual_income_30000_to_39999', 'pct_households_with_annual_income_40000_to_49999', 'pct_households_with_annual_income_50000_to_59999', 'pct_households_with_annual_income_60000_to_75499', 'pct_households_with_annual_income_75000_to_99999', 'pct_households_with_annual_income_less_than_30000', 'pct_in_labor_force_status_armed_forces', 'pct_in_labor_force_status_civilian_employed', 'pct_in_labor_force_status_civilian_unemployed', 'pct_pop_at_100_to_149_pct_poverty_level', 'pct_pop_at_or_above_150_pct_poverty_level', 'pct_pop_below_100_pct_poverty_level', 'pct_pop_employment_status_in_labor_force', 'pct_pop_employment_status_not_in_labor_force', 'pct_pop_received_ssi_foodstamps_snap_past_year', 'pct_pop_works_industry_agriculture_forestry_fishing_hunting_mining', 'pct_pop_works_industry_armed_forces', 'pct_pop_works_industry_arts_entertainment_food_services', 'pct_pop_works_industry_construction', 'pct_pop_works_industry_educational_healthcare_social_assistance', 'pct_pop_works_industry_finance_insurance_real_estate', 'pct_pop_works_industry_information', 'pct_pop_works_industry_manufacturing', 'pct_pop_works_industry_other_services', 'pct_pop_works_industry_professional_scientific_management', 'pct_pop_works_industry_public_administration', 'pct_pop_works_industry_retail_trade', 'pct_pop_works_industry_transportation_warehousing_utilities', 'pct_pop_works_industry_wholesale_trade', 'pct_pop_works_occupation_construction_maintenance', 'pct_pop_works_occupation_management_business_science_arts', 'pct_pop_works_occupation_military_related', 'pct_pop_works_occupation_production_transportation_moving', 'pct_pop_works_occupation_sales_office', 'pct_pop_works_occupation_service', 'pop_at_100_to_149_pct_poverty_level', 'pop_at_or_above_150_pct_poverty_level', 'pop_below_100_pct_poverty_level', 'pop_employment_status_in_labor_force', 'pop_employment_status_in_labor_force_armed_forces', 'pop_employment_status_in_labor_force_civilian_employed', 'pop_employment_status_in_labor_force_civilian_unemployed', 'pop_employment_status_not_in_labor_force', 'pop_received_ssi_foodstamps_snap_past_year', 'pop_total_y', 'pop_works_industry_agriculture_forestry_fishing_hunting_mining', 'pop_works_industry_armed_forces', 'pop_works_industry_arts_entertainment_food_services', 'pop_works_industry_construction', 'pop_works_industry_educational_healthcare_social_assistance', 'pop_works_industry_finance_insurance_real_estate', 'pop_works_industry_information', 'pop_works_industry_manufacturing', 'pop_works_industry_other_services', 'pop_works_industry_professional_scientific_management', 'pop_works_industry_public_administration', 'pop_works_industry_retail_trade', 'pop_works_industry_transportation_warehousing_utilities', 'pop_works_industry_wholesale_trade', 'pop_works_occupation_construction_maintenance', 'pop_works_occupation_management_business_science_arts', 'pop_works_occupation_military_related', 'pop_works_occupation_production_transportation_moving', 'pop_works_occupation_sales_office', 'pop_works_occupation_service', 'geometry', 'households_cohabiting_couple', 'households_cohabiting_couple_with_children', 'households_female_head', 'households_female_head_with_children', 'households_male_head', 'households_male_head_with_children', 'households_married_couple', 'households_married_couple_with_children', 'households_total_y', 'households_with_computing_devices_desktop_laptop', 'households_with_computing_devices_none', 'households_with_computing_devices_other_computer', 'households_with_computing_devices_smartphone', 'households_with_computing_devices_tablet', 'households_with_computing_devices_total', 'households_with_no_internet_access', 'pct_households_cohabiting_couple', 'pct_households_cohabiting_couple_with_children', 'pct_households_female_head', 'pct_households_female_head_with_children', 'pct_households_male_head', 'pct_households_male_head_with_children', 'pct_households_married_couple', 'pct_households_married_couple_with_children', 'pct_households_with_computing_devices_desktop_laptop', 'pct_households_with_computing_devices_none', 'pct_households_with_computing_devices_other_computer', 'pct_households_with_computing_devices_smartphone', 'pct_households_with_computing_devices_tablet', 'pct_households_with_computing_devices_total', 'pct_households_with_no_internet_access', 'pct_pop_adult_education_bachelors_or_higher', 'pct_pop_adult_education_high_school', 'pct_pop_adult_education_less_than_high_school', 'pct_pop_adult_education_some_college_or_associates', 'pct_pop_lived_in_same_house_last_year', 'pct_pop_veterans', 'pct_veterans_female', 'pct_veterans_male', 'pop_adult_education_bachelors_or_higher', 'pop_adult_education_high_school', 'pop_adult_education_less_than_high_school', 'pop_adult_education_some_college_or_associates', 'pop_lived_in_same_house_last_year', 'pop_total', 'pop_veterans', 'pop_veterans_female', 'pop_veterans_male']

### Dropping percentages and geometry

In [8]:
cols_to_drop = df_main.filter(like='pct').columns
df_main = df_main.drop(columns=cols_to_drop)

In [9]:
cols_to_drop = df_main.filter(like='geometry').columns
df_main = df_main.drop(columns=cols_to_drop)

In [10]:
df_main

,fips,Staffed_Beds,Total_Discharges,Patient_Days,Gross_Patient_Revenue,Hospitals,Local_Hospital,ADI_NATRANK,ADI_STATERNK,2021/3/10_x,...,households_with_no_internet_access,pop_adult_education_bachelors_or_higher,pop_adult_education_high_school,pop_adult_education_less_than_high_school,pop_adult_education_some_college_or_associates,pop_lived_in_same_house_last_year,pop_total,pop_veterans,pop_veterans_female,pop_veterans_male
0,1001,77.0,3049.0,15984.0,250284.0,1.0,yes,66.977778,4.355556,6400.0,...,3307,8464,8819,2886,9201,48039.0,55639,4559,542,4017
1,1003,301.0,18080.0,78361.0,2481966.0,3.0,yes,51.534483,2.655172,20012.0,...,10018,36513,29636,10250,34448,191350.0,218289,19174,1573,17601
2,1005,47.0,1055.0,4571.0,76099.0,1.0,yes,90.900000,7.950000,2161.0,...,2700,1409,4525,3131,3955,20996.0,25026,1340,107,1233
3,1007,156.0,229.0,1053.0,31288.0,1.0,yes,83.411765,6.647059,2469.0,...,1520,1388,5442,2189,3292,19347.0,22374,1205,63,1142
4,1009,0.0,0.0,0.0,0.0,0.0,no,72.325581,4.906977,6260.0,...,3920,4158,9757,4494,11023,52428.0,57755,3408,218,3190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,56037,58.0,1279.0,4742.0,207720.0,2.0,yes,54.088235,6.147059,3861.0,...,1498,5084,7298,1656,8906,34743.0,43352,2903,223,2680
3120,56039,121.0,1711.0,5932.0,273723.0,1.0,yes,6.473684,1.000000,3404.0,...,540,7762,2278,871,3390,18448.0,23356,827,98,729
3121,56041,32.0,803.0,1627.0,105109.0,1.0,yes,57.058824,7.117647,2084.0,...,531,1974,3960,664,3627,17520.0,20374,952,74,878
3122,56043,0.0,0.0,0.0,0.0,0.0,no,59.555556,7.777778,888.0,...,429,1013,1021,308,1457,6667.0,7933,588,23,565
3123,56045,0.0,0.0,0.0,0.0,0.0,no,63.600000,8.600000,623.0,...,367,668,1312,199,1346,5472.0,6942,558,40,518

### Model Fitting

In [11]:
df_main = df_main.drop(columns=['pop_total_x', 'pop_total_y'])

In [12]:
non_numeric_columns = df_main.select_dtypes(exclude='number').columns
print("Non-numeric columns:")
for column in non_numeric_columns:
    print(column)

Non-numeric columns:
Local_Hospital

In [13]:
df_main['Local_Hospital'] = df_main['Local_Hospital'].replace({'yes': 1, 'no': 0})

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [15]:
list(df_main.columns)

['fips',
 'Staffed_Beds',
 'Total_Discharges',
 'Patient_Days',
 'Gross_Patient_Revenue',
 'Hospitals',
 'Local_Hospital',
 'ADI_NATRANK',
 'ADI_STATERNK',
 '2021/3/10_x',
 '2022/3/10_x',
 '2023/3/10_x',
 '2021/3/10_y',
 '2022/3/10_y',
 '2023/3/10_y',
 'Value_education',
 'Value_poverty',
 'Value_unemployment',
 'pop_commute_departure_0000_to_0459',
 'pop_commute_departure_0500_to_0529',
 'pop_commute_departure_0530_to_0559',
 'pop_commute_departure_0600_to_0629',
 'pop_commute_departure_0630_to_0659',
 'pop_commute_departure_0700_to_0729',
 'pop_commute_departure_0730_to_0759',
 'pop_commute_departure_0800_to_0829',
 'pop_commute_departure_0830_to_0859',
 'pop_commute_departure_0900_to_0959',
 'pop_commute_departure_1000_to_1059',
 'pop_commute_departure_1100_to_1159',
 'pop_commute_departure_1200_to_1559',
 'pop_commute_departure_1600_to_2359',
 'pop_commute_travel_time_10_to_14_min',
 'pop_commute_travel_time_15_to_19_min',
 'pop_commute_travel_time_20_to_24_min',
 'pop_commute_travel_time_25_to_29_min',
 'pop_commute_travel_time_30_to_34_min',
 'pop_commute_travel_time_35_to_39_min',
 'pop_commute_travel_time_40_to_44_min',
 'pop_commute_travel_time_45_to_59_min',
 'pop_commute_travel_time_5_to_9_min',
 'pop_commute_travel_time_60_to_89_min',
 'pop_commute_travel_time_90_min_or_more',
 'pop_commute_travel_time_under_5_min',
 'pop_commutes_by_bicycle',
 'pop_commutes_by_car_truck_van_alone',
 'pop_commutes_by_car_truck_van_any',
 'pop_commutes_by_car_truck_van_carpool',
 'pop_commutes_by_public_transport_any',
 'pop_commutes_by_public_transport_bus',
 'pop_commutes_by_public_transport_ferry',
 'pop_commutes_by_public_transport_lightrail',
 'pop_commutes_by_public_transport_rail',
 'pop_commutes_by_public_transport_subway',
 'pop_commutes_by_taxi_motorcycle_or_other',
 'pop_commutes_by_walking',
 'pop_has_0_vehicles_available',
 'pop_has_1_vehicles_available',
 'pop_has_2_vehicles_available',
 'pop_has_3_or_more_vehicles_available',
 'pop_works_from_home',
 'pop_works_in_county_of_residence',
 'pop_works_in_state_different_county_of_residence',
 'pop_works_in_state_of_residence',
 'pop_works_outside_state_of_residence',
 'median_age',
 'median_age_female',
 'median_age_male',
 'pop_birthplace_foreign',
 'pop_birthplace_us',
 'pop_citizenship_non_us',
 'pop_citizenship_us_native',
 'pop_citizenship_us_naturalized',
 'pop_ethnicity_hispanic_latino',
 'pop_ethnicity_non_hispanic',
 'pop_race_asian',
 'pop_race_black',
 'pop_race_hawaiian_pacific_islander',
 'pop_race_multiple',
 'pop_race_native_american',
 'pop_race_other',
 'pop_race_white',
 'pop_sex_female',
 'pop_sex_female_age_10_to_14',
 'pop_sex_female_age_15_to_17',
 'pop_sex_female_age_18_to_19',
 'pop_sex_female_age_20',
 'pop_sex_female_age_21',
 'pop_sex_female_age_22_to_24',
 'pop_sex_female_age_25_to_29',
 'pop_sex_female_age_30_to_34',
 'pop_sex_female_age_35_to_39',
 'pop_sex_female_age_40_to_44',
 'pop_sex_female_age_45_to_49',
 'pop_sex_female_age_50_to_54',
 'pop_sex_female_age_55_to_59',
 'pop_sex_female_age_5_to_9',
 'pop_sex_female_age_60_to_61',
 'pop_sex_female_age_62_to_64',
 'pop_sex_female_age_65_to_66',
 'pop_sex_female_age_67_to_69',
 'pop_sex_female_age_70_to_74',
 'pop_sex_female_age_75_to_79',
 'pop_sex_female_age_80_to_84',
 'pop_sex_female_age_85_and_over',
 'pop_sex_female_age_under_5',
 'pop_sex_male',
 'pop_sex_male_age_10_to_14',
 'pop_sex_male_age_15_to_17',
 'pop_sex_male_age_18_to_19',
 'pop_sex_male_age_20',
 'pop_sex_male_age_21',
 'pop_sex_male_age_22_to_24',
 'pop_sex_male_age_25_to_29',
 'pop_sex_male_age_30_to_34',
 'pop_sex_male_age_35_to_39',
 'pop_sex_male_age_40_to_44',
 'pop_sex_male_age_45_to_49',
 'pop_sex_male_age_50_to_54',
 'pop_sex_male_age_55_to_59',
 'pop_sex_male_age_5_to_9',
 'pop_sex_male_age_60_to_61',
 'pop_sex_male_age_62_to_64',
 'pop_sex_male_age_65_to_66',
 'pop_sex_male_age_67_to_69',
 'pop_sex_male_age_70_to_74',
 'pop_sex_male_age_75_to_79',
 'pop_sex_male_age_80_to_84',
 'pop_sex_male_age_85_and_over',
 'pop_sex_male_age_under_5',
 'households_total_x',
 'households_with_annual_income_100000_to_124999',
 'households_with_annual_income_125000_to_149999',
 'households_with_annual_income_150000_to_199999',
 'households_with_annual_income_200000_or_more',
 'households_with_annual_income_30000_to_39999',
 'households_with_annual_income_40000_to_49999',
 'households_with_annual_income_50000_to_59999',
 'households_with_annual_income_60000_to_75499',
 'households_with_annual_income_75000_to_99999',
 'households_with_annual_income_less_than_30000',
 'pop_employment_status_in_labor_force',
 'pop_employment_status_in_labor_force_armed_forces',
 'pop_employment_status_in_labor_force_civilian_employed',
 'pop_employment_status_in_labor_force_civilian_unemployed',
 'pop_employment_status_not_in_labor_force',
 'pop_received_ssi_foodstamps_snap_past_year',
 'pop_works_industry_agriculture_forestry_fishing_hunting_mining',
 'pop_works_industry_armed_forces',
 'pop_works_industry_arts_entertainment_food_services',
 'pop_works_industry_construction',
 'pop_works_industry_educational_healthcare_social_assistance',
 'pop_works_industry_finance_insurance_real_estate',
 'pop_works_industry_information',
 'pop_works_industry_manufacturing',
 'pop_works_industry_other_services',
 'pop_works_industry_professional_scientific_management',
 'pop_works_industry_public_administration',
 'pop_works_industry_retail_trade',
 'pop_works_industry_transportation_warehousing_utilities',
 'pop_works_industry_wholesale_trade',
 'pop_works_occupation_construction_maintenance',
 'pop_works_occupation_management_business_science_arts',
 'pop_works_occupation_military_related',
 'pop_works_occupation_production_transportation_moving',
 'pop_works_occupation_sales_office',
 'pop_works_occupation_service',
 'households_cohabiting_couple',
 'households_cohabiting_couple_with_children',
 'households_female_head',
 'households_female_head_with_children',
 'households_male_head',
 'households_male_head_with_children',
 'households_married_couple',
 'households_married_couple_with_children',
 'households_total_y',
 'households_with_computing_devices_desktop_laptop',
 'households_with_computing_devices_none',
 'households_with_computing_devices_other_computer',
 'households_with_computing_devices_smartphone',
 'households_with_computing_devices_tablet',
 'households_with_computing_devices_total',
 'households_with_no_internet_access',
 'pop_adult_education_bachelors_or_higher',
 'pop_adult_education_high_school',
 'pop_adult_education_less_than_high_school',
 'pop_adult_education_some_college_or_associates',
 'pop_lived_in_same_house_last_year',
 'pop_total',
 'pop_veterans',
 'pop_veterans_female',
 'pop_veterans_male']

### Selecting Columns

In [16]:
df_main_selected = df_main[['Staffed_Beds', 'Total_Discharges', 'ADI_NATRANK', '2021/3/10_x',
 '2022/3/10_x',
 '2023/3/10_x',
 '2021/3/10_y',
 '2022/3/10_y',
 '2023/3/10_y',
 'Value_education',
 'Value_poverty',
 'Value_unemployment','pop_commutes_by_car_truck_van_any','pop_commutes_by_public_transport_any','median_age',
 'pop_citizenship_non_us',
 'pop_citizenship_us_native',
 'pop_citizenship_us_naturalized','pop_ethnicity_hispanic_latino',
 'pop_ethnicity_non_hispanic',
 'pop_race_asian',
 'pop_race_black',
 'pop_race_hawaiian_pacific_islander',
 'pop_race_multiple',
 'pop_race_native_american',
 'pop_race_other',
 'pop_race_white','pop_sex_female','pop_sex_male','households_with_annual_income_100000_to_124999',
 'households_with_annual_income_125000_to_149999',
 'households_with_annual_income_150000_to_199999',
 'households_with_annual_income_200000_or_more',
 'households_with_annual_income_30000_to_39999',
 'households_with_annual_income_40000_to_49999',
 'households_with_annual_income_50000_to_59999',
 'households_with_annual_income_60000_to_75499',
 'households_with_annual_income_75000_to_99999',
 'households_with_annual_income_less_than_30000','pop_employment_status_in_labor_force', 'pop_received_ssi_foodstamps_snap_past_year','households_with_no_internet_access',
 'pop_adult_education_bachelors_or_higher',
 'pop_adult_education_high_school',
 'pop_adult_education_less_than_high_school',
 'pop_adult_education_some_college_or_associates','pop_total']]

In [17]:
df_main_selected # still need age group

,Staffed_Beds,Total_Discharges,ADI_NATRANK,2021/3/10_x,2022/3/10_x,2023/3/10_x,2021/3/10_y,2022/3/10_y,2023/3/10_y,Value_education,...,households_with_annual_income_75000_to_99999,households_with_annual_income_less_than_30000,pop_employment_status_in_labor_force,pop_received_ssi_foodstamps_snap_past_year,households_with_no_internet_access,pop_adult_education_bachelors_or_higher,pop_adult_education_high_school,pop_adult_education_less_than_high_school,pop_adult_education_some_college_or_associates,pop_total
0,77.0,3049.0,66.977778,6400.0,15559.0,19790.0,93.0,208.0,232.0,21.714286,...,2893,6089,26025,3681,3307,8464,8819,2886,9201,55639
1,301.0,18080.0,51.534483,20012.0,55159.0,69860.0,293.0,657.0,727.0,21.928571,...,11536,18734,103116,7530,10018,36513,29636,10250,34448,218289
2,47.0,1055.0,90.900000,2161.0,5458.0,7485.0,51.0,94.0,103.0,22.285714,...,680,4147,9356,3088,2700,1409,4525,3131,3955,25026
3,156.0,229.0,83.411765,2469.0,6400.0,8091.0,60.0,100.0,109.0,21.571429,...,1129,2452,8970,1188,1520,1388,5442,2189,3292,22374
4,0.0,0.0,72.325581,6260.0,14861.0,18704.0,129.0,227.0,261.0,21.571429,...,2283,6372,24133,2749,3920,4158,9757,4494,11023,57755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,58.0,1279.0,54.088235,3861.0,9993.0,12507.0,36.0,123.0,139.0,22.360714,...,2212,3046,23009,1476,1498,5084,7298,1656,8906,43352
3120,121.0,1711.0,6.473684,3404.0,9598.0,12134.0,9.0,16.0,16.0,22.496429,...,1835,1162,15189,147,540,7762,2278,871,3390,23356
3121,32.0,803.0,57.058824,2084.0,4866.0,6406.0,12.0,37.0,43.0,22.500000,...,1634,1573,10178,456,531,1974,3960,664,3627,20374
3122,0.0,0.0,59.555556,888.0,1612.0,2755.0,26.0,43.0,51.0,22.710714,...,440,720,4018,169,429,1013,1021,308,1457,7933
3123,0.0,0.0,63.600000,623.0,1206.0,1905.0,5.0,18.0,23.0,22.567857,...,510,824,3028,145,367,668,1312,199,1346,6942

In [18]:
X = df_main.drop(columns=['fips','2021/3/10_x', '2022/3/10_x', '2023/3/10_x', '2021/3/10_y', '2022/3/10_y', '2023/3/10_y'])
y = df_main['2021/3/10_y']